### ISSUE TITLE
[PE-D][Tester E] Application crashes when adding website that isn't in correct format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T15-2/tp#107]
Application requests for website URL upon creating a new entry.

When adding a website that is not in the proper format (eg: google1), the application displays an error and crashes.

![image.png](https://raw.githubusercontent.com/hrithie/ped/main/files/f9efc15e-dc9c-4420-b7f8-fe9ded2099ec.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: hrithie/ped#2

**Comment by kairuler** [comment]
Changed the accepted URL format to include URLs without "." (e.g. `google` instead of `google.com`)
