### ISSUE TITLE
[PE-D][Tester C] Delete command does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T15-2/tp#109]
![Screenshot 2023-03-31 at 5.09.51 PM.png](https://raw.githubusercontent.com/anthea-pr0g/ped/main/files/559bdb1e-ae8d-4d1f-a64a-d5aa66fcce00.png)
I cannot delete the password based on the  UG 
They are also  not clear "The hash or name of the password can be used" what is the hash of the password and where can that be found.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: anthea-pr0g/ped#5

**Comment by kairuler** [comment]
Delete command is update. Now works.
However, UG needs to be updated to removed the "hash" part because delete only works with password name, not hash.
