### ISSUE TITLE
[PE-D][Tester E] Password shown in plain text

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T15-2/tp#110]
It is best practise to ensure passwords are never shown in plain text, even when the user is inputting it to deter attacks like shoulder surfing. 

A suggestion could be to not display to users what they have typed as the password and ask them to re-enter it to confirm it is accurate.

![image.png](https://raw.githubusercontent.com/hrithie/ped/main/files/03b2cdd3-731f-4ce7-8cec-12088d2623d2.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: hrithie/ped#3

**Comment by kairuler** [comment]
Maybe can implement?
Top comment on [this stackoverflow post](https://stackoverflow.com/questions/10819469/hide-input-on-command-line) gives a solution.
