### ISSUE TITLE
[PE-D][Tester E] UG does not show the flow of how application works

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-2/tp#113]
The instruction given in the UG is not clear enough as it does not show the flow of the application. Providing screenshots of the flow could help users to understand how your application works better in terms of `add` command. 

With the current explanation, I thought I would be saving the password using the first command, however I was wrong:

![image.png](https://raw.githubusercontent.com/hrithie/ped/main/files/129b4425-85b9-423e-a963-0fec9175f533.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: hrithie/ped#4

**Comment by kairuler** [comment]
UG is clear enough.
