### ISSUE TITLE
[PE-D][Tester E] Functionality does not work as stated in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T15-2/tp#123]
The application is supposed to request a secret password from the user. However, it displays the password of the user without any verification.

This is bad security, especially when dealing with passwords.

![image.png](https://raw.githubusercontent.com/hrithie/ped/main/files/cfde6f6e-75ab-493d-8e09-25d75e141560.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: hrithie/ped#5

**Comment by kairuler** [comment]
Possible to implement something like 2FA in the future.
