### ISSUE TITLE
[PE-D][Tester A] Save method doesn't work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T15-2/tp#124]
If entering save, it says this method cannot be called. Although I see from my trails that after I restart the program, it can read in information automatically.

![989c2fc2ce84c73ce80ebbd564b5b76.png](https://raw.githubusercontent.com/FanZixian/ped/main/files/fcc1361a-190b-4b7b-a041-8ba3e543c42d.png)

And the local repo, doesn't contain anything.

![image.png](https://raw.githubusercontent.com/FanZixian/ped/main/files/0fd7b84f-24e1-42e4-b04f-a90be4139ef8.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: FanZixian/ped#10

**Comment by kairuler** [comment]
Save command works now.
