### ISSUE TITLE
[PE-D][Tester D] Possible incorrect creation of WIfiPassword

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-2/tp#126]
When the user tries to create a new wifi password, the question prompted is not relevant to the creation(asking for Student ID?)

![image.png](https://raw.githubusercontent.com/ghzr0/ped/main/files/181481df-2feb-4816-8d80-d5e5bd1a9739.png)

In addition, the created password storage format called from the 'list' command may not be correct?

![image.png](https://raw.githubusercontent.com/ghzr0/ped/main/files/889e2165-8f4d-4509-ac78-4ea17327940b.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ghzr0/ped#5

**Comment by kairuler** [comment]
Resolved #122
