### ISSUE TITLE
[PE-D][Tester D] Edit command too lengthy

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-2/tp#141]
To call the edit command [edit p/PASSWORD_NAME [-f nf/NEW_FOLDER_NAME] [-d nd/NEW_DESCRIPTION] [-N np/NEW_PASSWORD_NAME] ], the user has to type a very lengthy input, maybe could simplify to easier inputs?

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ghzr0/ped#9

**Comment by kairuler** [comment]
edit command has been updated to make it simpler to type. now, users just need to enter `edit PASSWORD_NAME`.
