### ISSUE TITLE
[PE-D][Tester C] Explanation is too brief for view command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T15-2/tp#143]
![Screenshot 2023-03-31 at 6.37.30 PM.png](https://raw.githubusercontent.com/anthea-pr0g/ped/main/files/d2d0f7c7-1d38-4842-831a-8709ae978508.png)

I am not sure how "For passwords that are “password-required”, a secret password is required to reveal." I can do this setting if I want to, maybe it is possible to explain further how this can be done. 

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: anthea-pr0g/ped#17

**Comment by kairuler** [comment]
@DeepanjaliDhawan could you help to remove the line: "For passwords that are “password-required”, a secret password is required to reveal." in the UG? We are no longer implementing this feature. Thanks!

**Comment by DeepanjaliDhawan** [comment]
Updated the view command with updated features

**Comment by kairuler** [comment]
Resolved
