### ISSUE TITLE
[PE-D][Tester C] Help and Menu could be the same feature with different commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-2/tp#145]
![Screenshot 2023-03-31 at 7.03.23 PM.png](https://raw.githubusercontent.com/anthea-pr0g/ped/main/files/3a2b90da-93f1-4cee-97d2-bc54c738abfc.png)

![Screenshot 2023-03-31 at 7.03.34 PM.png](https://raw.githubusercontent.com/anthea-pr0g/ped/main/files/30399df8-d636-45a9-998d-f2834f8cec95.png)

unsure if help and menu were meant to be the same feature , but it seems there is inconsistency in the UG

"help" doesn't work but "menu" does

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: anthea-pr0g/ped#19

**Comment by ollayf** [comment]
now merged as "menu" function

**Comment by ollayf** [comment]
@DeepanjaliDhawan for your action on UG side

**Comment by ollayf** [comment]
@DeepanjaliDhawan for your action on UG side

**Comment by DeepanjaliDhawan** [comment]
Done
