### ISSUE TITLE
[PE-D][Tester B] Password doesn't accept special characters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T15-2/tp#149]
![image.png](https://raw.githubusercontent.com/Masahiro21/ped/main/files/93a6577a-c470-42a1-9a16-9e6270d89f6b.png)

password in the basic password input field doesn't accept special characters

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Masahiro21/ped#1

**Comment by ollayf** [comment]
done
