### ISSUE TITLE
[PE-D][Tester B] Delete command on an empty list

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-2/tp#152]
![image.png](https://raw.githubusercontent.com/Masahiro21/ped/main/files/0e1719a3-eb82-4ef2-9e8c-6803c0397187.png)

delete command on an empty list causes the program to crash and restart, should add exception handling for this to allow users to continue using the program

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Masahiro21/ped#4

**Comment by ollayf** [comment]
solved
