### ISSUE TITLE
[PE-D][Tester B] Save function does not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-2/tp#154]
![image.png](https://raw.githubusercontent.com/Masahiro21/ped/main/files/f840c6ff-7484-4acc-904f-1437c092a0ec.png)

calling the save command doesn't save the passwords to a text file, there isn't an output ./logs/out/ to save to. This means load function doesn't work also.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Masahiro21/ped#6

**Comment by euzhengxi** [comment]
save command has been implemented, the load command has been removed
