### ISSUE TITLE
Code Review: Deepanjali

### ISSUE THREAD

**Issue by mathanmahe** [AY2223S2-CS2113-T15-2/tp#166]
@DeepanjaliDhawan

1. Indentation of wrapped lines should be 8 spaces - Line 58
![image](https://user-images.githubusercontent.com/77711860/229486553-823eff1c-3b09-467c-bdbb-0e043841b85d.png)

2. Comments should be indented relative to their position in the code - Line  25,30
![image](https://user-images.githubusercontent.com/77711860/229486579-900556cf-9cca-4b59-b631-8ea7eb45549b.png)

3. Comments should be indented relative to their position in code - Line 32, 38
![image](https://user-images.githubusercontent.com/77711860/229490569-c48ad461-c9c7-4f02-aa3b-98fb33bf00c5.png)

4. Line 5,8 - Delete dead comments/import statements that are no longer used
![image](https://user-images.githubusercontent.com/77711860/229486692-ce1fdbb2-61b6-411f-abd0-586030aeea2d.png)

**Comment by ollayf** [comment]
resolved
