### ISSUE TITLE
Code Review - Zheng Xi

### ISSUE THREAD

**Issue by mathanmahe** [AY2223S2-CS2113-T15-2/tp#167]
@euzhengxi

1. Consider using white space to seaparate logical sections of the code - Line 92 and Line 97
![image](https://user-images.githubusercontent.com/77711860/229491616-141c92aa-8598-47c1-9459-cea6ca743eb8.png)

2. Line 116, 143 - Consider rephrasing to write comments to the reader

![image](https://user-images.githubusercontent.com/77711860/229492544-4cf07520-34d1-4e07-b850-3cf3fcfa87e4.png)

3. Line 193- Avoid complicated expressions 
   1. consider breaking it down into intermediate variables for added clarity
   ![image](https://user-images.githubusercontent.com/77711860/229491639-2fc01ca7-488d-4d31-bf8c-5ad176c9784c.png)

4. Line 117-145: Avoid magic numbers. Consider using intermediate variables to denote repeated indices like input[2],input[3]
That usually share the same meaning.

![image](https://user-images.githubusercontent.com/77711860/229491662-5654a329-545a-4c3f-b1a4-fe19f37b596b.png)

**Comment by ollayf** [comment]
resolved
