### ISSUE TITLE
Code Review: Khairul

### ISSUE THREAD

**Issue by mathanmahe** [AY2223S2-CS2113-T15-2/tp#168]
@kairuler

1. Avoid using magic strings - Line 69, 87, 89. Consider making constant messages that can be called to improve readability.

![image](https://user-images.githubusercontent.com/77711860/229492848-4e66fc5e-08be-49d3-b0de-ce349724e451.png)

2. Avoid using magic strings - Line 33,34,36

![image](https://user-images.githubusercontent.com/77711860/229492899-3fba16cd-a9e1-423b-aebb-0d49a2dce4d0.png)

3. Constant should be in uppercase, using underscore to separate words - Line 13

![image](https://user-images.githubusercontent.com/77711860/229492933-ff5b7a55-6e8f-4cff-9ffe-ca3f7d50e7c6.png)

4. Consider making these final constants, if they are not going to change.

![image](https://user-images.githubusercontent.com/77711860/229492970-1518c47f-3878-4594-895b-2a70d3b27aa0.png)

**Comment by ollayf** [comment]
resolved
