### ISSUE TITLE
Code Review: Yu Fei

### ISSUE THREAD

**Issue by mathanmahe** [AY2223S2-CS2113-T15-2/tp#169]
@ollayf

1. Line 18 - Consider writing comments to the reader, instead of as a note to self. 
![image](https://user-images.githubusercontent.com/77711860/229493468-59b9d330-2f7e-4012-b5cc-6ea016fbbccb.png)

2. Line 20, 25, 30 Comments should be indented relative to their position in code.
![image](https://user-images.githubusercontent.com/77711860/229493496-b059be0c-56b5-4144-a2e6-4c81a4b7a53d.png)

3. Line 207 - Comment minimally but sufficiently. Since code is self explanatory, can consider removing this comment.
![image](https://user-images.githubusercontent.com/77711860/229493521-65ad5ba1-4168-461d-820d-e2c8153d598f.png)

4. Line 35,36,49 - Avoid magic strings. Consider extracting out a constant such as `FOLDER_DELIMITER` to improve readability and allow reuse.

![image](https://user-images.githubusercontent.com/77711860/229493554-96505043-37f0-423c-ba51-d7e5def06259.png)

5. Line 99 - Avoid notes to self while commenting and consider rephrasing it to write to the reader.

6. Final constants hould be in uppercase where each word is separated by an underscore
![image](https://user-images.githubusercontent.com/77711860/229493585-58a5ba85-75a7-4bf1-81b2-b89246713457.png)

**Comment by ollayf** [comment]
resolved
