### ISSUE TITLE
Team Testing - Showing the password in list even after exiting the program and running the jar again.

### ISSUE THREAD

**Issue by DeepanjaliDhawan** [AY2223S2-CS2113-T15-2/tp#196]
Ran a JAR file, created a new password and exited the program
![image](https://user-images.githubusercontent.com/80743735/230301767-c7bae80d-3029-437b-9cf2-d301a09fbeee.png)
 
After exiting, created 2 new passwords
![image](https://user-images.githubusercontent.com/80743735/230301987-17d5121c-49e3-40a2-9c76-66270f71e70b.png)

Listed the passwords
![image](https://user-images.githubusercontent.com/80743735/230302059-6594e917-35d8-4320-babd-356b3fac410f.png)

The password created in the first run of the jar file is also saved.. Note: I didn't type the `save` command yet..

**Comment by kairuler** [comment]
Its a feature
