### ISSUE TITLE
Team Testing - Minor changes in menu

### ISSUE THREAD

**Issue by DeepanjaliDhawan** [AY2223S2-CS2113-T15-2/tp#198]
![image](https://user-images.githubusercontent.com/80743735/230302691-ecd01474-6114-4ff8-81f7-3e30e50503e0.png)

Can keep the indentation of the new password option the same for a higher readability
eg: 1. Add a general password: new [PASSWORD_NAME] [f/FOLDER_NAME]
         Add Credit Card details: new o/CreditCard [NAME] [f/FOLDER_NAME]
         Add details for a Crypto Wallet: new o/Crypto [NAME] [f/FOLDER_NAME]
         Add a NUSNet ID and Password: new o/NUSNet [NAME] [f/FOLDER_NAME]
         Add a NUS StudentID details (starting with A and ends with capital Alphabet): new o/StudentID [NAME] [f/FOLDER_NAME]
         Add a password for Wifi: new o/WifiPassword [NAME] [f/FOLDER_NAME]
     2. Delete the unwanted secrets: delete

**Comment by ollayf** [comment]
I disagree with this... precisely why I added the indentation compared to previous. So many similar commands that it's hard for users to read. But the reality is that not all of them are of the same prioirity.

**Comment by ollayf** [comment]
unless you have a better example i will not be updating this
