### ISSUE TITLE
Team Testing - small recommendation for adding name for creditcard

### ISSUE THREAD

**Issue by DeepanjaliDhawan** [AY2223S2-CS2113-T15-2/tp#200]
![image](https://user-images.githubusercontent.com/80743735/230303808-fb756092-6b74-4a90-bcc6-ac768e3e44be.png)
Usually creditcard numbers are written as 4 characters with a space in between

Can consider allowing this option of leaving space b/w every 4 characters..

**Comment by ollayf** [comment]
nice to have but problematic to check... wont be bothering to do this
