### ISSUE TITLE
Team Testing - Add CryptoWallet

### ISSUE THREAD

**Issue by kairuler** [AY2223S2-CS2113-T15-2/tp#201]
For adding a new password, putting an invalid option like `o/InvalidOption` would correctly produce an error message.

However, putting `o/CryptoWallet` crashes the program.

![image](https://user-images.githubusercontent.com/78406251/230305350-4263ee54-41f7-46b1-90be-f76f492858f3.png)

I'm not sure what type of `o/` input reproduces this bug because I only managed to reproduce it using `o/CryptoWallet`.

**Comment by ollayf** [comment]
resolved
