### ISSUE TITLE
Team Testing - Remove confusion between NUSID and NUS Student ID

### ISSUE THREAD

**Issue by DeepanjaliDhawan** [AY2223S2-CS2113-T15-2/tp#214]
![image](https://user-images.githubusercontent.com/80743735/230318565-cb19909c-63e4-44c9-964c-3e4de956e7b1.png)

Have to clarify the difference between NUSID and NUSStudentID (in UG and menu)

**Comment by ollayf** [comment]
change to what?

**Comment by DeepanjaliDhawan** [comment]
Like u mentioned in the NUS Student ID details a bracket, can mention the same in NUSNet id as well

eg:
```
Add NUSNET ID (eg: e0123456)
Add NUS StudentID (eg: A0123456B)
```

**Comment by ollayf** [comment]
ok this is quite a good idea!
