### ISSUE TITLE
Team Testing - Making c/ more clear

### ISSUE THREAD

**Issue by DeepanjaliDhawan** [AY2223S2-CS2113-T15-2/tp#215]
![image](https://user-images.githubusercontent.com/80743735/230319905-dd7657b3-72a1-4fe1-b10c-ac2d6440da72.png)

To update the menu and UG to state that it is not a command used alone... It has to be used in a middle of when the features are running.. 

basically making it more clear..

**Comment by ollayf** [comment]
can you write out an example?

**Comment by ollayf** [comment]
and the line cannot be too long too

**Comment by DeepanjaliDhawan** [comment]
it can be written in the menu: 
`To cancel the operation at any point. note that it should only be used during a feature's execution and not as a separate command on its own: \c' 

i suggest that let this be the same in menu... But I'll add this line in the UG..

**Comment by ollayf** [comment]
btw its not \c its c/

**Comment by ollayf** [comment]
done
