### ISSUE TITLE
Team Testing - make it clear for the user if the above has been deleted

### ISSUE THREAD

**Issue by DeepanjaliDhawan** [AY2223S2-CS2113-T15-2/tp#219]
![image](https://user-images.githubusercontent.com/80743735/230329229-9324ff43-8dd7-47bb-9360-73dc9d32d5e7.png)

Instead of blank space can use 
```
password name deleted
```

**Comment by ollayf** [comment]
fixed

**Comment by ollayf** [comment]
fixed
