### ISSUE TITLE
Team Testing - Masking Student ID

### ISSUE THREAD

**Issue by DeepanjaliDhawan** [AY2223S2-CS2113-T15-2/tp#220]
![image](https://user-images.githubusercontent.com/80743735/230383903-1da24fa1-9152-49e7-a50c-1e344df1fdfc.png)

I don't think that student ID is sensitive information... so maybe there is no need to mask it.

**Comment by ollayf** [comment]
Should hide for your side in list also... it is sensitive information. If i have your matric number u know what i can do on behalf of you? O.O
