### ISSUE TITLE
Final Test - UG (Search)

### ISSUE THREAD

**Issue by euzhengxi** [AY2223S2-CS2113-T15-2/tp#251]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/85627654/230805854-67ba5518-2c5d-499d-9bce-15068e948e47.png">

search command is search password f/folder not search n/password f/folder

**Comment by DeepanjaliDhawan** [comment]
![image](https://user-images.githubusercontent.com/80743735/230836494-dc74abf5-1522-49e8-9323-0f99680aeb25.png)

i didnt write n/password
