### ISSUE TITLE
Final Test - UG (arrow keys)

### ISSUE THREAD

**Issue by euzhengxi** [AY2223S2-CS2113-T15-2/tp#252]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/85627654/230805992-e2b652dd-8464-4e4a-aeef-f1c98ede42e5.png">

should make it know to users that they usage of arrow keys (like how you can go to the previous command in CLI using the up key) results in errors

**Comment by euzhengxi** [comment]
so far all arrow keys result in errors for me

**Comment by DeepanjaliDhawan** [comment]
For me the up error is good as it helps me review past commands.. 

I think the arrow keys functionality depends on terminal to terminal..
