### ISSUE TITLE
Final Test - UG (Ctrl C)

### ISSUE THREAD

**Issue by euzhengxi** [AY2223S2-CS2113-T15-2/tp#253]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/85627654/230806096-da3be835-8af4-4581-b6f9-1594c762abae.png">

Should make it known to users that Ctrl C and Ctrl V should not be used in the program. Ctrl C kills the program prematurely, Ctrl V cannot function if Ctrl C cannot be used. Users can only copy and paste information by selecting it, copying and pasting MANUALLY

**Comment by DeepanjaliDhawan** [comment]
Ctrl - V works for me... 

Will mention that Ctrl - C leads to cancelling the program 

But keeping in consideration the error part... Will add a question like that in FAQ, and urge users to refrain from using the CLI key commands.
