### ISSUE TITLE
Final Test - UG (UI - save)

### ISSUE THREAD

**Issue by euzhengxi** [AY2223S2-CS2113-T15-2/tp#255]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/85627654/230808170-81a79787-0f3e-45da-a5e6-b481e3261305.png">

data is being saved  but the Ui is not printing out the save message.

**Comment by ollayf** [comment]
in this case, unless the person presses saves, the message will not keep coming up. it is annoying

**Comment by DeepanjaliDhawan** [comment]
Yesterday @ollayf solved this issue so updated the UG with the new screenshot
