### ISSUE TITLE
Final Test - UG (documentation fix)

### ISSUE THREAD

**Issue by euzhengxi** [AY2223S2-CS2113-T15-2/tp#256]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/85627654/230808364-c0810338-42e0-455a-b57f-ac914a6f9da2.png">

All data is saved the moment it is added / edited / deleted (i checked it but yall can double check). so in a sense no data is unsaved unless the user cancels the operation, in which it will not save either way. So it might be good to amend the description?

**Comment by DeepanjaliDhawan** [comment]
Removed `save the unsave secrets` to save all secrets. 

Also mentioned that all secrets will be saved subsequently until the user does not cancel the operation  using `c/` command..
